version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile.integration-tests
    volumes:
      - "./integration-tests:/integration-tests"
      - "./screenshots:/screenshots"
    command: "wait-for-it.sh web:80 -- mocha --timeout 50000 --recursive /integration-tests"
    depends_on:
      - web
      - googlechrome-headless
      - googlechrome-full

  web:
    image: tutum/hello-world
    expose:
      - "80"
 
  googlechrome-headless:
    image: justinribeiro/chrome-headless
    cap_add:
      - "SYS_ADMIN"
    expose:
      - "9222"
    ports:
      - "9222:9222"

  googlechrome-full:
    image: siomiz/chrome
    ports:
      - "5900:5900"
    volumes:
      - "./screenshots:/screenshots"

